#!/bin/bash
pip3 install pandas fastapi uvicorn requests beautifulsoup4 --break-system-packages --ignore-installed
ufw allow 8000/tcp
python3 /usr/local/bin/app.py
systemctl daemon-reload
systemctl enable --now app.service
